spring.application.name=EVSapp

# ===============================
# DATABASE (Railway OR Local)
# ===============================
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/event_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# PORT (Railway dynamic)
# ===============================
server.port=${PORT:8080}